#!/usr/bin/env python3
import sys
import json
import yaml
import argparse
from collections import OrderedDict
from yaml import Dumper

# We should keep the order of the original json by using an OrderedDict and instructing
# yaml.dump to use it
def dict_representer(dumper, data):
  return dumper.represent_dict(data.items())

Dumper.add_representer(OrderedDict, dict_representer)

parser = argparse.ArgumentParser()
parser.add_argument('json_file', nargs='?', type=argparse.FileType('r'), default=sys.stdin)

json_file = parser.parse_args().json_file
json_body = json.loads(json_file.read(), object_pairs_hook=OrderedDict)
yaml_body = yaml.dump(json_body, Dumper=Dumper, default_flow_style=False)
print(yaml_body, end='')

