#!/usr/bin/env python3
import sys
import json
import yaml
import argparse
from collections import OrderedDict
from yaml import Loader
from yaml.representer import SafeRepresenter

tag = yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG

def dict_constructor(loader, node):
  return OrderedDict(loader.construct_pairs(node))

Loader.add_constructor(tag, dict_constructor)

parser = argparse.ArgumentParser()
parser.add_argument('yaml_file', nargs='?', type=argparse.FileType('r'), default=sys.stdin)

yaml_file = parser.parse_args().yaml_file
yaml_body = yaml.load(yaml_file, Loader=Loader)
json_body = json.dumps(yaml_body, indent=3)
print(json_body, end='')
